#
# Docker image for financial data-science project using Python.
#

FROM --platform=linux/amd64 ubuntu:latest

# Install non-Python package dependencies
# And clean up for minimizing the Docker image size.
RUN apt-get update && apt-get -y upgrade \
    && apt-get install -y --no-install-recommends \
        git \
        # git-lfs \
        wget \
        g++ \
        gcc \
        vim \
        ca-certificates \
        && rm -rf /var/lib/apt/lists/* \
        apt-get clean

# install Miniconda
ENV PATH="/root/miniconda3/bin:$PATH"
ARG PATH="/root/miniconda3/bin:$PATH"
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh \
    && conda init bash \
    && . /root/.bashrc \
    && conda update conda

# install some python packages
RUN conda install -y \
    pip \
    numpy \
    scipy \
    matplotlib \
    pandas \
    scikit-learn \
    ipython \
    jupyterlab
RUN conda clean -ay
RUN pip install notebook cython yfinance jupyter

# ENTRYPOINT ["/bin/bash", "-l", "-c"]
# CMD ["ipython"]

EXPOSE 8888
# ENTRYPOINT ["jupyter", "notebook", "--no-browser", "--ip=0.0.0.0","--NotebookApp.token=''", "--NotebookApp.password=''"]


# start the jupyter notebook in server mode
CMD ["conda", "run", "-n", "trading_env", "jupyter","notebook","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root", "--notebook-dir=/notebooks"]

# alternatively start the jupyter-lab notebook in server mode
#CMD ["conda", "run", "-n", "trading_env", "jupyter-lab","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root", "--notebook-dir=/notebooks"]